#name: Junit test and Checkstyle
name: test

on: [ push ]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  call-workflow-passing-data:
    uses: EWU-CSCD212/cscd212-s23-jar-tests-files/.github/workflows/lab5.yml@main
